### PR TITLE
fix #1132: The entirety of JUnit XML files is skipped if they are minified

### LINKED ISSUE #1132: The entirety of JUnit XML files is skipped if they are minified
I'm using py.test and its built-in JUnit XML generator to make reports of my tests. Go.cd always fails to display any of the contents, logging this:

```
13:16:44.907 Unable to publish test properties. Error was javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The element type "all-results" must be terminated by the matching end-tag "</all-results>".
13:16:44.912 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.913 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.914 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.915 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```

Now, bear with me here, cause I have zero knowledge of Java, but skimming through the source I think the issue is that the py.test JUnit files have no newlines in them, so [this line](https://github.com/gocd/gocd/blob/ed4536974c8e08d996ca3c8f8daf20d830696fad/config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java#L158) skips the complete file, with its 200 test cases. ~~If that's not the problem, please let me know and I'll edit the title of this issue.~~ _Edit:_ I tried reformatting the same XML file and it works now. This means that there's a workaround:
# Workaround
1. Install the `xmllib2-utils` package on your agents
2. Change your py.test config to output to `junit.min.xml` instead of `junit.xml`
3. Add the following step to the end of the pipeline:

``` xml
<exec command="/bin/bash">
  <arg>-c</arg>
  <arg>xmllint --format junit.min.xml > junit.xml</arg>
  <runif status="passed" />
</exec>
```

### PR DESCRIPTION
**Pull request by xli**
Fix  #1132, changes:
* Use Jdom to parse out unit test report xml file instead of using regex expression, when merging all test files
* Output message when a test report xml file can't be parsed as XML document

### CODE REVIEW

**Comment by arvindsv** [comment]
@xli: Nice! First PR! It makes sense to me (the changes) and the PR build passed (though it did not update GitHub). Need to check why.

I don't really understand why the previous code was excluding the prolog. Maybe having the prolog will cause a problem somewhere? Let's see what others think.

Congratulations!! Hopefully, this is the first of many PRs. :)

**Comment by ketan** [comment]
The intent of this code is to "concatenate" multiple XML test result files into one, so that go can run one giant XSLT operation on it. This XSLT output then seems to go to the failures tab.

Since each individual test report XML would have the XML prolog in it, a simple concat would not work. Hence the stripping of the prolog. I think @xli's solution is much neat; so wow; very awesome. I'll look at this by EOD.

Welcome on board, good to have you!

File: config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java [hunk 1]
```diff
@@ -151,18 +154,12 @@ private void pumpFileContentIfValid(PrintStream out, File testFile) throws IOExc
...
-                out.println(line);
-            }
-            while ((line = bufferedReader.readLine()) != null) {
-                out.println(line);
-            }
-        } finally {
-            IOUtils.closeQuietly(bufferedReader);
+            String content = FileUtil.readToEnd(file).trim();
+            final Document document = XmlUtils.buildXmlDocument(content);
+            out.println(XmlUtils.asXml(document.getRootElement()));
```
Comment (ketan) [inline config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java]: If you use `XmlUtils.writeXml(Document, OutputStream)`, this new impl (`XmlUtils.asXml(Element)`) is redundant. Feel free to rename that method if you feel it appropriate.

File: common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml [hunk 2]
```diff
@@ -1,4 +1,4 @@
-﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
+<?xml version="1.0" encoding="utf-8" standalone="no"?>
```
Comment (ketan) [inline common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml]: I think you may have removed the BOM there, was that intentional?

**before:**

```
$ file common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml
common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml: XML 1.0 document, UTF-8 Unicode (with BOM) text
```

**after:**

```
$ file common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml
common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml: XML 1.0 document, ASCII text
```

File: config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java (hunk 1 above)
Comment (xli) [inline config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java]: writeXml(Document, OutputStream) will output "<?xml version="1.0" encoding="utf-8"?>"

File: common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml (hunk 2 above)
Comment (xli) [inline common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml]: With BOM, it is not a valid xml file.

Comment (arvindsv) [inline common/test-resources/unit/data/NunitTestResultWithByteOrderMark.xml]: I think the test name suggests that the BOM was left there intentionally.

**Comment by xli** [comment]
Reverted NunitTestResultWithByteOrderMark.xml changes. Handles BOM after read file content. Using regex /^\W+</ to clean it up is the simplest one in our case.

**Comment by ketan** [comment]
Hey @xli - a commit message containing `fix(es) #number` will close the original issue when the PR gets merged, which means it falls through the cracks as far as QA is concerned. For the future please don't write `fix(es) or close(s)` in the commit message :) Just mentioning the original issue `#number` should be sufficient to tie PRs to issues. #githubGotchas
