### PR TITLE
Websocket communication (#1793): change back to use Java serialization

### LINKED ISSUE #1958: Environment variable GO_FROM_REVISION always set to the latest revision
Issue observed on 16.3.0-3055(2dcbbfe1a7b44897bc026b845c6b0822a27858a8), not observed on 16.2.1-3027

Steps to reproduce:

- Create a pipeline with git material(or any SCM)
- Add/modify files in git repo to create multiple revisions
- Trigger pipeline
- Check the value of GO_FROM_REVISION on the console
- The value is same as the GO_TO_REVISION even though there are more than one revision
- Expect the GO_FROM_REVISION to reflect the exact revision number from which the material update starts

### PR DESCRIPTION
**Pull request by xli**
We will change to JSON format when we have better protocal designed for agent and server communication (proposed by #1954).
Also remove all JSON serialization related optimization. Serialize BuildWork same with before, reduce the chance having problem.

This change should fix #1958 when websocket is enabled.

### CODE REVIEW

File: common/src/com/thoughtworks/go/websocket/Message.java [hunk 1]
```diff
@@ -16,27 +16,24 @@
...
 
     public static byte[] encode(Message msg) {
-        String encode = JsonMessage.encode(msg);
         ByteArrayOutputStream bytes = new ByteArrayOutputStream();
         try {
-            GZIPOutputStream out = new GZIPOutputStream(bytes);
-            out.write(encode.getBytes(StandardCharsets.UTF_8));
-            out.finish();
+            GZIPOutputStream zip = new GZIPOutputStream(bytes);
+            ObjectOutputStream output = new ObjectOutputStream(zip);
```
Comment (jyotisingh) [inline common/src/com/thoughtworks/go/websocket/Message.java]: Need to `close` these streams

**Comment by ketan** [comment]
@xli and @wpc — next time you update a PR to address any feedback, please be sure to leave a note. GitHub does not send a notification when a PR is updated and it gets difficult for the original reviewer to know if the PR was updated without visiting the PR page.
