### PR TITLE
Fix startup scripts

### LINKED ISSUE #1460: Running 15.3.0(2409-0256d8f868257a) fails to start
Starting the new servers ends up running:
```
exec /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -jar '"/bin/agent-bootstrapper.jar"' server 8153
```
at the end of the startup script. Note the extraneous quotes on the bootstrapper.jar. This then elicits:

```
Error: Unable to access jarfile "/bin/agent-bootstrapper.jar"
```

Which looks right because you think the quotes are there to be helpful, but they're not, it is literally trying to execute a file located at `./"/bin/agent-bootstrapper.jar"`.

### PR DESCRIPTION
**Pull request by arvindsv**
Commit messages should be descriptive. This should be easy to verify.

Functional tests should be changed to use these scripts, and not their own.

Fixes #1460.

### CODE REVIEW

**Comment by arvindsv** [comment]
Fixes #1460.

File: installers/agent/release/agent.sh [hunk 1]
```diff
@@ -101,15 +98,18 @@ AGENT_STARTUP_ARGS="-Dcruise.console.publish.interval=10 -Xms$AGENT_MEM -Xmx$AGE
 if [ "$TMPDIR" != "" ]; then
     AGENT_STARTUP_ARGS="$AGENT_STARTUP_ARGS -Djava.io.tmpdir=$TMPDIR"
 fi
+if [ "$USE_URANDOM" != "false" ] && [ -e "/dev/urandom" ]; then
+    AGENT_STARTUP_ARGS="$AGENT_STARTUP_ARGS -Djava.security.egd=file:/dev/./urandom"
```
Comment (ketan) [inline installers/agent/release/agent.sh]: Why can't this just be `/dev/urandom` ?

File: installers/agent/release/agent.sh [hunk 2]
```diff
@@ -101,15 +98,18 @@ AGENT_STARTUP_ARGS="-Dcruise.console.publish.interval=10 -Xms$AGENT_MEM -Xmx$AGE
...
 export LOG_FILE
 
 CMD="$JAVA_HOME/bin/java -jar \"$AGENT_DIR/agent-bootstrapper.jar\" $GO_SERVER $GO_SERVER_PORT"
 
-echo "[`date`] Starting Go Agent Bootstrapper with command: $CMD" >>$LOG_FILE
-echo "[`date`] Starting Go Agent Bootstrapper in directory: $AGENT_WORK_DIR" >>$LOG_FILE
-echo "[`date`] AGENT_STARTUP_ARGS=$AGENT_STARTUP_ARGS" >>$LOG_FILE
+echo "[`date`] Starting Go Agent Bootstrapper with command: $CMD" >>"$LOG_FILE"
+echo "[`date`] Starting Go Agent Bootstrapper in directory: $AGENT_WORK_DIR" >>"$LOG_FILE"
+echo "[`date`] AGENT_STARTUP_ARGS=$AGENT_STARTUP_ARGS" >>"$LOG_FILE"
```
Comment (ketan) [inline installers/agent/release/agent.sh]: Backticks are deprecated. The correct way to go about this is `echo "$(date) AGENT_STARTUP_ARGS=$AGENT_STARTUP_ARGS" >>"$LOG_FILE"`

File: installers/agent/release/agent.sh (hunk 1 above)
Comment (arvindsv) [inline installers/agent/release/agent.sh]: Due to this [old bug](http://bugs.java.com/view_bug.do?bug_id=6202721), but that has been fixed in later versions. I guess it can be changed now.

File: installers/agent/release/agent.sh (hunk 2 above)
Comment (arvindsv) [inline installers/agent/release/agent.sh]: Correct. There are many more issues with the script. The way quoted params are being handled, etc. It needs a more comprehensive testing and fixing cycle. This was just about spaces in the filename. Wasn't looking at much else.

File: installers/agent/release/agent.sh (hunk 1 above)
Comment (ketan) [inline installers/agent/release/agent.sh]: Can you submit a PR to change it?

**Comment by ketan** [comment]
oh great sage of the land of bash, @mavcunha would you mind helping us with your amazing bash chops.

File: installers/agent/release/agent.sh (hunk 1 above)
Comment (arvindsv) [inline installers/agent/release/agent.sh]: I'll have to check whether it is fixed. That bug was marked as "Not an issue", with the suggestion that people use `new SecureRandom()` instead. We have no control over it.

Comment (arvindsv) [inline installers/agent/release/agent.sh]: No. It doesn't look like it is fixed yet.

```
$ cat JRand.java
import java.security.SecureRandom;
class JRand {
  public static void main(String args[]) throws Exception {
    System.out.println("Ok: " +
      SecureRandom.getInstance("SHA1PRNG").nextLong());
  }
}

$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: -4364682451133414604

real    0m0.129s
user    0m0.120s
sys     0m0.020s

$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: -9054433491496715268

real    0m0.130s
user    0m0.130s
sys     0m0.010s

$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: 7166545031684433590

real    0m0.125s
user    0m0.130s
sys     0m0.020s

$ time java JRand
[STUCK]
```

Did a `kill -3` and found this in the stack trace:

```
"main" prio=10 tid=0x00007feef000a000 nid=0x44 runnable [0x00007feef9141000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:272)
        at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
        at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
        at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:197)
        at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:214)
        - locked <0x00000000f229f3d8> (a sun.security.provider.SecureRandom)
        at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
        - locked <0x00000000f229fcc8> (a java.security.SecureRandom)
        at java.security.SecureRandom.next(SecureRandom.java:477)
        at java.util.Random.nextLong(Random.java:334)
        at JRand.main(JRand.java:4)
```

Then, killed that and tried this:

```
$ time java -Djava.security.egd=file:/dev/urandom JRand
```

Stuck again and still the same stack trace:

```
"main" prio=10 tid=0x00007f518400a000 nid=0xa6 runnable [0x00007f518daca000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:272)
        at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
        at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
        at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:197)
        at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:214)
        - locked <0x00000000f229f3d8> (a sun.security.provider.SecureRandom)
        at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
        - locked <0x00000000f229fcc8> (a java.security.SecureRandom)
        at java.security.SecureRandom.next(SecureRandom.java:477)
        at java.util.Random.nextLong(Random.java:334)
        at JRand.main(JRand.java:4)
```

`/dev/./urandom` still works fine:

```
$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: 338890852372789233

real    0m0.191s
user    0m0.120s
sys     0m0.020s

$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: -1104126029115977571

real    0m0.122s
user    0m0.120s
sys     0m0.010s

$ time java -Djava.security.egd=file:/dev/./urandom JRand
Ok: 5840685795943611680

real    0m0.127s
user    0m0.130s
sys     0m0.010s
```

All of this was tried on Centos running on docker. strace shows both files are opened, in both cases, though. Probably, in the /dev/./urandom case, it doesn't try reading from it.

```
$ strace -f -e file java -Djava.security.egd=file:/dev/urandom JRand 2>&1 | grep random
[pid   156] stat("/dev/random", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 8), ...}) = 0
[pid   156] stat("/dev/urandom", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
[pid   156] open("/dev/random", O_RDONLY) = 12
[pid   156] open("/dev/urandom", O_RDONLY) = 13
[pid   156] open("/dev/random", O_RDONLY) = 14
^C
[WAS STUCK]

$ strace -f -e file java -Djava.security.egd=file:/dev/./urandom JRand 2>&1 | grep random
[pid   181] stat("/dev/random", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 8), ...}) = 0
[pid   181] stat("/dev/urandom", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
[pid   181] open("/dev/random", O_RDONLY) = 12
[pid   181] open("/dev/urandom", O_RDONLY) = 13
[pid   181] open("/dev/./urandom", O_RDONLY) = 14
```

**Comment by rajiesh** [comment]
functional test updated to use the regular agent script for tests too fixed by gocd/functional-tests#6

**Comment by rajiesh** [comment]
acceptance and regression tests successful after this change. Agent startup scripts have been used in all tests and no failures observed https://build.go.cd/go/pipelines/regression-gauge/34/regression-linux/1
