### PR TITLE
fix #2071: git repo get unshallowed unnecessarily on agent side

### LINKED ISSUE #2071: Agent side git repo get unshallowed unnecessarily
##### Issue Type

- Bug Report

##### Summary

Current git shallow clone implementation has a issue on agent side. After initial build on agent with  shallow clone, the following build on same agent will unshallow the local repository unnecessarily there is new changes pushed to remote git repository. This kind of defeat the purpose of shallow cloning.  

###### Basic environment details
* Go Version: current trunk

##### Steps to Reproduce

1.  Setup a pipeline with git material and shallow clone 
2.  Trigger first build
3.  Confirm repository cloned in agent working dir is shallow (git log show history is truncated)
4.  Push some changes to remote repository
5.  Check repository cloned in agent working dir is shallow

##### Expected Results
The repo should remain shallow.

##### Actual Results
The repos get unshallowed.

### PR DESCRIPTION
**Pull request by wpc**
This PR fix issue #2071. It fixes a mistake I made in #1846: unshallow check was put before git fetch.

### CODE REVIEW

**Comment by arvindsv** [comment]
Hi @wpc. Sorry for the delay. It looks good to me. @varshavaradarajan is taking a look at it and will merge it soon. This will (almost certainly) go into 16.3 itself. It looks like it should.

**Comment by wpc** [comment]
@arvindsv 
np.
> This will (almost certainly) go into 16.3 itself. It looks like it should.

If shallow clone feature goes into 16.3, then this fix certainly should. Otherwise the shallow clone feature is just a waste in most of the cases on agent side.

File: common/test/unit/com/thoughtworks/go/domain/materials/git/GitCommandTest.java [hunk 1]
```diff
@@ -196,7 +196,7 @@ public void shouldBombForFetchAndResetFailureWhileFetching() throws IOException
     @Test
     public void shouldBombForFetchAndResetFailureWhileReseting() throws IOException {
```
Comment (varshavaradarajan) [inline common/test/unit/com/thoughtworks/go/domain/materials/git/GitCommandTest.java]: Could you please change the name since you are not doing a fetch?

File: common/test/unit/com/thoughtworks/go/domain/materials/git/GitCommandTest.java [hunk 2]
```diff
@@ -225,7 +225,7 @@ public void shouldBombForFetchAndResetWhenSubmoduleUpdateFails() throws Exceptio
```
Comment (varshavaradarajan) [inline common/test/unit/com/thoughtworks/go/domain/materials/git/GitCommandTest.java]: Could you please change the name of the test here as well? :)

**Comment by wpc** [comment]
@varshavaradarajan I have rename the tests as you suggested. Good catch! Thank you :+1: 

> please update the copyright on GitCommand Test?

Are we sure we want to do this? My understanding of copyright notice year is "year of first publication of the work" (http://www.copyrightlaws.com/copyright-basics/copyright-notice-year/), in another word it is how far back your claim is effective. I don't know in which year gocd became open source, but 2016 seems not right.

-- wpc

**Comment by varshavaradarajan** [comment]
Well, the general practice on the team has been to update it whenever there is a change to the code specific to a particular file. This way it shows the year of the last revision made. May be @arvindsv or @jyotisingh could explain more about why it is so? Looks fine functionality wise. :+1:

**Comment by ketan** [comment]
WPC is correct about the copyright years. I've been doing it wrong on the
go team, and the team  followed suit.

**Comment by arvindsv** [comment]
> WPC is correct about the copyright years. I've been doing it wrong on the
go team, and the team  followed suit.

Not true. This is what I had got from the lawyers around the end of 2014:

> Lawyer: And as the project progresses, with each new file that we add or modify, we should update the copyright year to the current year.
> Me: You're saying that we shouldn't change all "Copyright 2014" to "Copyright 2015" in the beginning of 2015? Is this right?
> Lawyer: Yes.
> Me: We should change only the files added or modified.
> Lawyer: and Yes.

So, yes, please change it to 2016.

**Comment by arvindsv** [comment]
Also, the link WPC points to says this:

> For constantly evolving websites and blogs that contain works published over several years, the notice may include a range of years (e.g., 2009-2013), starting from the date of the oldest published elements and ending with the date of the newest published elements.

Maybe that's what it is in play here? But, it was quite clear from the conversation I had that the year needs to be updated.

**Comment by wpc** [comment]
@arvindsv, That's very weird. But anyway the notice year is just educational and I will make the change.
