### PR TITLE
Pipeline Config API bug fixes #1630, #1417

### LINKED ISSUE #1630: Issues Observed in Pipeline config API
Tested pipeline config API on 15.3.0-2663 and below issues are observed,

~~Issue 1:~~
~~environment variables: Not validates for unique values, does not validate for special chars.if '#' char is present then it checks and throws error but other chars are not checked

eg:
```
"environment_variables": [
    {
      "secure": false,
      "name": "java%",
      "value": "java21"
    },
    {
      "secure": false,
      "name": "java",
      "value": "java2"
    }
  ]
```

```
"environment_variables": [
    {
      "secure": false,
      "name": "java",
      "value": "java21"
    },
    {
      "secure": false,
      "name": "java",
      "value": "java2"
    }
  ]
```

~~Issue 2~~:

working directory validation do not look for special chars: Below value is accepted
>"working_directory": "some../..rm” 

**Issue 3**:
* Create a pipeline with template(vis UI, config API still do not support create templates)
* Perform a GET on the config API
Json contains below stage value which needs to be removed in case of pipelines using template

> "stage" : null

* Similarly when pipeline is defined by stages, the template property should not be returned by the config API. Currently the response for GET API has

> "template": null

~~Issue 4:~~
* Add github-pr-poller plugin to the go server
* create a pipeline with GitHub material and no path blacklisted
* perform a GET on config API for this pipeline
* In the Json response Material contains the SCM ref and also "filter". Filter value is set to null
* Now make modifications to the pipeline and perform PUT 
* Response received is "500 Server Error" - since the filter value was null and API does not accpet null value for SCM filter
* 'null' value should be accepted for SCM filter ~~

Additional issues identified:

**Issue 5**:

GET Pipeline Config API do not have scm material destination.
* Create a pipeline with 2 materials - github material(precondition: add github.pr plugin to server) and another one
* Specify a destination folder for scm material
* Perform a GET pipeline config request
* response json do not contain the destination folder. here is the snippet of the response,

> {
      "type": "plugin",
      "attributes": {
        "ref": "b337590b-919f-41f7-91de-55aa5d805147",
        "filter": null
      }
    }

* Take this response json and do a PUT on pipeline config API -  Response is 422(Unprocessible entity) but the response body do not have any details of what is the failure
* Actually the failure is that since there are 2 materials and the scm material do not have destination set the request is not processed

**Issue 6**:

GET Pipeline config API returns 500 Server error if the pipeline has an On Cancel Task added for any task. Below exception observed in the logs,

> 2015-11-27 14:18:04,831 FATAL [qtp1963576789-24] Rails:? -
NameError (uninitialized constant ApiV1::Config::Tasks::OnCancelRepresenter::UrlBuilder):
  app/presenters/api_v1/config/tasks/on_cancel_representer.rb:30:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/controllers/api_v1/admin/pipelines_controller.rb:26:in `show'
  lib/jetty_weak_etag_middleware.rb:13:in `call'
  lib/catch_json_parse_errors.rb:8:in `call’

**Issue 7**:

Pipeline Config API allows pipeline to be created/updated with template AND stage defined. 

* Create a template via UI
* Create a pipeline with "template" property value set to the template created.
* Also define the stage object with proper stage items
* A POST or a PUT request for this request json will be successful
* The UI will show 2 stages on the pipeline dashboard page
* However the pipeline config page stage tab will show only the template

### PR DESCRIPTION
**Pull request by juhijariwala**

### CODE REVIEW

File: config/config-api/src/com/thoughtworks/go/config/ValidationContext.java [hunk 1]
```diff
@@ -49,5 +51,9 @@
     SecurityConfig getServerSecurityConfig();
 
     boolean doesTemplateExist(CaseInsensitiveString template);
+
+    SCM findScm(String scmID);
```
Comment (ketan) [inline config/config-api/src/com/thoughtworks/go/config/ValidationContext.java]: Can we rename this to `findScmById`?

Comment (juhijariwala) [inline config/config-api/src/com/thoughtworks/go/config/ValidationContext.java]: I will do that.

File: server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb [hunk 2]
```diff
@@ -39,17 +39,21 @@ def type
...
-        end
+      private
+      def error_keys
+        {"src" => "source", "dest" => "destination"}
+      end
 
-        mapped_errors
+      def matching_error_key key
+        return error_keys[key] if error_keys[key]
+        key
```
Comment (ketan) [inline server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb]: `error_keys[key] || key` reads better :)

I like this pattern. Can we extract this into a class with usage that looks like this, and use it everywhere?

```ruby
def errors
  ErrorMapper.new(artifact.errors, 'src' => 'source', 'dest' => 'destination').mapped_errors
end
```

Comment (ketan) [inline server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb]: Also, this is a good place to use `inject` instead of `each` —

Comment (ketan) [inline server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb]:
```ruby
artifact.errors.inject({}) do |memo, (key, value)|
  translated_key = error_keys[key] || key
  memo[translated_key] = value
  memo
end
```

File: config/config-api/src/com/thoughtworks/go/config/ValidationContext.java [hunk 3]
```diff
@@ -49,5 +51,9 @@
...
+
+    PackageRepository findPackage(String packageId);
```
Comment (ketan) [inline config/config-api/src/com/thoughtworks/go/config/ValidationContext.java]: `byId` here too?

File: server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb (hunk 2 above)
Comment (ketan) [inline server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/artifact_representer.rb]: On second thought — this DSL probably reads better —

```ruby
class FooRepresenter < BaseRepresenter
    has_errors('src' => 'source', 'dest' => 'destination')
end
```

and let `has_errors` meta-program the necessary methods. Ping me or @maheshp if you'd like to understand this better.
