### PR TITLE
5587 warning in logs in rerunning job

### LINKED ISSUE #5587: Re-running failed jobs leaves a warning with null exception in the logs
##### Issue Type
- Bug Report

##### Summary

On re-running failed jobs from the jobs tab on stage details a null exception is thrown in the logs with a large stack trace. While this does not block the job assignment this can flood the logs.

###### Basic environment details

* Go Version: Go Version: 18.12.0-8203
* JAVA Version: Java10
* OS: MacOS(zip-installer)
* Browser vendor and version (if relevant): Chrome-71

##### Steps to Reproduce

1. Configure a pipeline with a job to fail
2. Run the pipeline
3. Once the job is failed, navigate to jobs tab from stage details page
4. Click on re-run failed jobs

##### Expected Results
The logs should not be flooded

##### Actual Results
The logs are flooded

##### Log snippets
```
2018-12-17 18:17:49,890 WARN  [qtp1944798106-32] Stage:434 - Expected stage [StageIdentifier[fail-rerun-pipeline, 7, 7, defaultStage, 1]] to have no state, but was Failed
java.lang.Exception: null
	at com.thoughtworks.go.domain.Stage.building(Stage.java:434)
	at com.thoughtworks.go.server.service.StageService.lambda$save$0(StageService.java:234)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.StageService.save(StageService.java:233)
	at com.thoughtworks.go.server.service.ScheduleService.lambda$scheduleStage$0(ScheduleService.java:228)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.ScheduleService.scheduleStage(ScheduleService.java:210)
	at com.thoughtworks.go.server.service.ScheduleService.internalRerun(ScheduleService.java:206)
	at com.thoughtworks.go.server.service.ScheduleService.lockAndRerunStage(ScheduleService.java:312)
	at com.thoughtworks.go.server.service.ScheduleService.rerunJobs(ScheduleService.java:334)
	at com.thoughtworks.go.server.service.ScheduleService.rerunFailedJobs(ScheduleService.java:371)
	at jdk.internal.reflect.GeneratedMethodAccessor639.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:470)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:328)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:57)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:199)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:103)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
	at org.jruby.RubyClass.finvoke(RubyClass.java:525)
	at org.jruby.RubyBasicObject.send(RubyBasicObject.java:1752)
	at org.jruby.RubyKernel.send(RubyKernel.java:2182)
	at org.jruby.RubyKernel$INVOKER$s$send.call(RubyKernel$INVOKER$s$send.gen)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:105)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.basic_implicit_render.invokeSuper2:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.basic_implicit_render.RUBY$method$send_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:176)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:72)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.invokeOther0:send_action(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rendering.invokeSuper6:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rendering.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.zSuperSplatArgs(IRRuntimeHelpers.java:1127)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.invokeSuper2:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.RUBY$block$process_action$1(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:162)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:134)
	at org.jruby.ir.runtime.IRRuntimeHelpers.yieldSpecific(IRRuntimeHelpers.java:463)
	at org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:119)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.RUBY$method$run_callbacks$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:187)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.invokeOther6:run_callbacks(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rescue.invokeSuper0:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rescue.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.zSuperSplatArgs(IRRuntimeHelpers.java:1127)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.invokeSuper3:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:38)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.RUBY$block$process_action$1(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:38)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:162)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:459)
	at org.jruby.ir.targets.YieldSite.yield(YieldSite.java:92)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.RUBY$block$instrument$1(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:162)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:459)
	at org.jruby.ir.targets.YieldSite.yield(YieldSite.java:92)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.instrumenter.RUBY$method$instrument$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:111)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:187)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:209)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:218)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.invokeOther5:instrument(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.RUBY$method$instrument$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:111)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:187)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:209)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:218)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.invokeOther43:instrument(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.params_wrapper.invokeSuper20:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.params_wrapper.RUBY$method$process_action$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:176)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.invokeOther11:process_action(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.RUBY$method$process$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
	at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionview_minus_5_dot_2_dot_1.lib.action_view.rendering.invokeSuper5:-unknown-super-target-(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionview_minus_5_dot_2_dot_1.lib.action_view.rendering.RUBY$method$process$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:98)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.invokeOther2:process(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.RUBY$method$dispatch$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:127)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:219)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:230)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.invokeOther10:dispatch(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.RUBY$method$dispatch$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:127)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:219)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:230)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther0:dispatch(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$dispatch$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$dispatch$0$__VARARGS__(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:88)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:176)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther6:dispatch(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$serve$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.invokeOther27:serve(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.RUBY$block$serve$1(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:162)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1801)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:147)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:156)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.invokeOther37:each(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.RUBY$method$serve$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther5:serve(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.versionist_minus_1_dot_7_dot_0.lib.versionist.middleware.invokeOther63:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:39)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.versionist_minus_1_dot_7_dot_0.lib.versionist.middleware.RUBY$method$_call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:39)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.versionist_minus_1_dot_7_dot_0.lib.versionist.middleware.invokeOther1:_call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:17)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.versionist_minus_1_dot_7_dot_0.lib.versionist.middleware.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:17)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.tempfile_reaper.invokeOther8:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.tempfile_reaper.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.etag.invokeOther5:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.etag.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.conditional_get.invokeOther14:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.conditional_get.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.head.invokeOther5:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.head.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.http.content_security_policy.invokeOther2:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.http.content_security_policy.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at uri_3a_classloader_3a_.jruby.rack.session_store.invokeOther2:call(uri:classloader:/jruby/rack/session_store.rb:79)
	at uri_3a_classloader_3a_.jruby.rack.session_store.RUBY$method$context$0(uri:classloader:/jruby/rack/session_store.rb:79)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:75)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:98)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.invokeOther0:context(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.cookies.invokeOther2:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.cookies.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.callbacks.invokeOther1:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.callbacks.RUBY$block$call$1(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:162)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:134)
	at org.jruby.ir.runtime.IRRuntimeHelpers.yieldSpecific(IRRuntimeHelpers.java:463)
	at org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:119)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.RUBY$method$run_callbacks$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:187)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.callbacks.invokeOther5:run_callbacks(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.callbacks.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.debug_exceptions.invokeOther2:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.debug_exceptions.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.show_exceptions.invokeOther2:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.show_exceptions.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.rack.logger.invokeOther11:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.rack.logger.RUBY$method$call_app$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:114)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:187)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:199)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.rack.logger.invokeOther10:call_app(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:28)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.rack.logger.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:28)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.remote_ip.invokeOther7:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.remote_ip.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.request_id.invokeOther7:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.request_id.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.method_override.invokeOther9:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.method_override.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.runtime.invokeOther2:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.runtime.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.cache.strategy.local_cache_middleware.invokeOther6:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.cache.strategy.local_cache_middleware.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.executor.invokeOther4:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.executor.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.static.invokeOther13:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.static.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.sendfile.invokeOther13:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.sendfile.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.engine.invokeOther3:call(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524)
	at Users.adityas.Downloads.test_installers.go_minus_server_minus_18_dot_12_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.railties_minus_5_dot_2_dot_1.lib.rails.engine.RUBY$method$call$0(/Users/adityas/Downloads/test_installers/go-server-18.12.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at uri_3a_classloader_3a_.rack.handler.servlet.invokeOther4:call(uri:classloader:/rack/handler/servlet.rb:22)
	at uri_3a_classloader_3a_.rack.handler.servlet.RUBY$method$call$0(uri:classloader:/rack/handler/servlet.rb:22)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:101)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:154)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
	at org.jruby.RubyClass.finvoke(RubyClass.java:911)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:356)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:369)
	at org.jruby.javasupport.JavaEmbedUtils$1.callMethod(JavaEmbedUtils.java:117)
	at org.jruby.rack.DefaultRackApplication.call(DefaultRackApplication.java:64)
	at org.jruby.rack.AbstractRackDispatcher.process(AbstractRackDispatcher.java:33)
	at org.jruby.rack.AbstractServlet.service(AbstractServlet.java:34)
	at org.jruby.rack.AbstractServlet.service(AbstractServlet.java:40)
	at com.thoughtworks.go.rackhack.DelegatingServlet.service(DelegatingServlet.java:48)
	at com.thoughtworks.go.rackhack.DelegatingServlet.service(DelegatingServlet.java:53)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:420)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73)
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilterInternal(FlashLoadingFilter.java:39)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.DenyIfRefererIsNotFilesFilter.doFilterInternal(DenyIfRefererIsNotFilesFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.VerifyAuthorityFilter.doFilterInternal(VerifyAuthorityFilter.java:58)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractUserEnabledCheckFilter.doFilterInternal(AbstractUserEnabledCheckFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.ThreadLocalUserFilter.doFilterInternal(ThreadLocalUserFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.filterWhenSecurityDisabled(AbstractBasicAuthenticationFilter.java:113)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.doFilterInternal(AbstractBasicAuthenticationFilter.java:71)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.AssumeAnonymousUserFilter.doFilterInternal(AssumeAnonymousUserFilter.java:65)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.doFilterInternal(AbstractReAuthenticationFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.InvalidateAuthenticationOnSecurityConfigChangeFilter.doFilterInternal(InvalidateAuthenticationOnSecurityConfigChangeFilter.java:101)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.RememberLastRequestUrlFilter.doFilterInternal(RememberLastRequestUrlFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:76)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:36)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-12-17 18:17:57,014 INFO  [101@MessageListener for WorkFinder] BuildAssignmentService:174 - [Agent Assignment] Assigned job [JobIdentifier[fail-rerun-pipeline, 7, 7, defaultStage, 2, defaultJob, 60]] to agent [Agent [in-adityas.local, 127.0.0.1, 9cad08f3-3597-4503-b67d-d448c19c1587]]
```

### LINKED ISSUE #6376: Rerun old stage failing without providing console output
[Raising a new issue based on a comment in #1996]

We are experiencing a similar issue -- We are trying to go back in our pipeline history and manually invoke the second stage of in a previous pipeline.  We see in the go-server.log file  that that the stage is being assigned.  However, after that the job is marked as failed.  There is no console output in the job detail tab, nor can we find any corresponding error message or stack traces in the go-server or go-agent log files.

this is what we see in our log file:

```
go-server.log:2019-05-31 16:15:13,113 INFO  [qtp1166807841-17] ScheduleService:230 - [Stage Schedule] Scheduling stage publish_x for pipeline myapp_release
go-server.log:2019-05-31 16:15:20,068 INFO  [101@MessageListener for WorkFinder] BuildAssignmentService:191 - [Agent Assignment] Assigned job [JobIdentifier[myapp_release, 84, 2.3.5.84, publish_x, 9, aws, 50810]] to agent [Agent [ip-10-100-14-193.mydomain, 10.100.14.193, 194988d9-53e3-4f57-9a21-e38c53fdbc9d]]
```

The other thing thing to note is that even though we see in the go-server.log file that the stage is being assigned,   on the detail page for the failed job we see this `AGENT: Not yet assigned (Unknown)`.
There are two bits of information that might be playing a role here that are worth sharing:

- We have recently changed the underlying template for the pipeline. So the template that was active when the original pipeline first stage ran is no longer active.  However, the names of the stages and jobs within the pipeline remained the same.

- For one of the materials in the pipeline, the current definition points to a different git branch that it did when the pipeline run we are trying to run the second stage on.

In our case, these are our environment details:

###### Basic environment details

* Go Version: `19.4.0`
* JAVA Version: `1.8.0_101`
* OS: `Linux 3.10.0-327.28.2.el7.x86_64`

(We had noticed this problem on GoCD 19.3.0)

Not sure how to proceed in further troubleshooting this.  Any help would be greatly appreciated.

_Originally posted by @dlethin in https://github.com/gocd/gocd/issues/1996#issuecomment-497781524_

### PR DESCRIPTION
**Pull request by msaurabh1978**
Fixed 2 related issues: #5587 & #6376 

Fixed #5587 - by removing the statement that logs the warning message. Please check the issue comments section for a detailed description of why this change was made. 

Fixed #6376 - by making sure that whenever job fails due to stale material config (meaning material config changed, either by modification or removal of existing material config, after it was run successfully before and then previous stages are run from history after this material config change)  then log an error message to console and also log exception with a proper message in the server logs.

aa
bb

### CODE REVIEW

File: server/src/main/java/com/thoughtworks/go/server/service/ScheduledPipelineLoader.java [hunk 1]
```diff
@@ -133,11 +130,15 @@ private MaterialConfigs knownMaterials(Pipeline pipeline, MaterialRevisions sche
...
+    private void appendToConsoleLog(JobInstance jobInstance, String message, String description) {
         try {
-            consoleService.appendToConsoleLog(jobInstance.getIdentifier(), "\n" + message + "\n");
+            consoleService.appendToConsoleLog(jobInstance.getIdentifier(), "\n" + message + "\n\n" + description + "\n");
         } catch (Exception e) {
             throw new RuntimeException(e);
         }
     }
+
+    private String joinTwoStringsWithNewLine(String str1, String str2){
```
Comment (GaneshSPatil) [inline server/src/main/java/com/thoughtworks/go/server/service/ScheduledPipelineLoader.java]: inline this?

File: server/src/main/java/com/thoughtworks/go/server/service/ScheduledPipelineLoader.java [hunk 2]
```diff
@@ -78,16 +80,11 @@ public Pipeline pipelineWithPasswordAwareBuildCauseByBuildId(final long buildId)
...
-                    @Override public void afterCommit() {
-                        final ServerHealthState error = ServerHealthState.error(message, description, HealthStateType.general(HealthStateScope.forJob(jobInstance.getPipelineName(), jobInstance.getStageName(), jobInstance.getName())));
-                        error.setTimeout(Timeout.FIVE_MINUTES);
-                        serverHealthService.update(error);
-                        appendToConsoleLog(jobInstance, message);
-                        appendToConsoleLog(jobInstance, description);
-                    }
-                });
-                throw new StaleMaterialsOnBuildCause(message);
+                final ServerHealthState error = ServerHealthState.error(message, description, HealthStateType.general(HealthStateScope.forJob(jobInstance.getPipelineName(), jobInstance.getStageName(), jobInstance.getName())));
```
Comment (bdpiparva) [inline server/src/main/java/com/thoughtworks/go/server/service/ScheduledPipelineLoader.java]: This is already fixed in PR #6410
